### DISCUSSION TITLE
Bring window controls closer to Adwaita

### DISCUSSION THREAD

**Discussion by danirabbit** [elementary/stylesheet#1204] [Ideas]
![Screenshot from 2022-05-07 14 41 37](https://user-images.githubusercontent.com/7277719/167272553-900d9fcb-0262-4b05-956c-8519f6bbf967.png)

```css
windowcontrols button {
border-radius: 99px;
background: alpha(@text_color, 0.1);
-gtk-icon-shadow: none;
padding: 2px;
margin: 3px;
}

window {
border-radius: 9px;
}
```

Making the corners rounder and adding a background behind window controls would make Adwaita apps feel a lot closer to the native look
