### ISSUE TITLE
Add subtle button shadows

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#188]
@danrabbit and I were looking at how to increase the difference between normal and disabled button states. One idea was to add a subtle shadow to buttons, then remove it from disabled buttons.

**Comment by cassidyjames** [comment]
As a super rough prototype I was playing with something like this:

```css
button:not(:checked) {
    box-shadow: 0 2px 3px rgba(0, 0, 0, 0.125);
}
```

It would need a *lote* more specific rules and tons of testing, but here's Widget Factory:

![image](https://user-images.githubusercontent.com/611168/66153873-88f60800-e5d9-11e9-8fe2-4cb0d47abefe.png)
