### ISSUE TITLE
Extend the Gtk.STYLE_CLASS_FLAT to Gtk.ActionBars too

### ISSUE THREAD

**Issue by lainsce** [elementary/stylesheet#225]
This new Flat class could also be used in Gtk.ActionBars, since those are also part of the window controls, and could have the option to be styled as Flat similarly to Gtk.HeaderBars.

Here's a relevant CSS to get started to adding this:
```css
actionbar,
.action-bar {
    border-top-color: transparent;
    background: @colorPrimary;
    color: @textColorPrimary;
    box-shadow:
        inset 1px 0 0 0 alpha (shade (@colorPrimary, 1.4), 0.6),
        inset -1px 0 0 0 alpha (shade (@colorPrimary, 1.4), 0.6),
        inset 0 -1px 0 0 alpha (shade (@colorPrimary, 1.4), 0.8);
}
```
