### ISSUE TITLE
Seekbar contrast in dark theme

### ISSUE THREAD

**Issue by peteruithoven** [elementary/stylesheet#270]
One of my smaller annoyances with elementary Videos is how hard it is to see how far along a video is. This is mostly caused by the lack of contrast in the dark themes seekbar. 
For reference a screenshot of Videos in Loki:
![screenshot from 2018-02-10 10 22 43](https://user-images.githubusercontent.com/523210/36060604-6497092e-0e4d-11e8-8d67-a5581e1ec811.png)

A screenshot of the latest master branch of Videos on github:
![screenshot from 2018-02-10 10 25 04](https://user-images.githubusercontent.com/523210/36060607-6e560ee2-0e4d-11e8-83c8-0c2479d907b0.png)

The contrast in the light theme seekbar seems a lot better, for reference Videos in light theme:
![screenshot from 2018-02-10 10 34 18](https://user-images.githubusercontent.com/523210/36060651-fd725590-0e4d-11e8-9db5-7d91c1945095.png)

## Comparison 
The seekbar in Youtube:
![screenshot from 2018-02-10 11 31 23](https://user-images.githubusercontent.com/523210/36061153-868374d8-0e56-11e8-8408-f55d9eb6161a.png)

Videos in Arc-solid theme:
![screenshot from 2018-02-10 11 34 35](https://user-images.githubusercontent.com/523210/36061155-8ab8350c-0e56-11e8-8b0c-e556ab481637.png)

Looking into this, I understand a [Gtk.Scale](https://valadoc.org/gtk+-3.0/Gtk.Scale.html) is used, which style is overriden in the elementary stylesheet. 
I think the colors are defined here:
https://github.com/elementary/stylesheet/blob/master/gtk-3.0/gtk-widgets-dark.css#L112-L193

# Some experiments:

## White
Matching the other ui elements on the bottom bar
![0 7 - 0 6](https://user-images.githubusercontent.com/523210/36067305-af65ae98-0eba-11e8-862f-768541015cb7.png)

``` css
.scale.highlight.left {
    border-color: alpha (#000, 0.5);
    background-image:
        linear-gradient(
            to bottom,
            alpha (
                #fff,
                0.7
            ),
            alpha (
                #fff,
                0.6
            )
        );
}
```
## Blue
Copied gradient from dark checkbox svg.

![checkbox blue](https://user-images.githubusercontent.com/523210/36067429-64300c22-0ebd-11e8-8af8-19da17afb598.png)

``` css
.scale.highlight.left {
    border-color: alpha (#000, 0.5);
    background-image:
        linear-gradient(
            to bottom,
            alpha (
                #55c1ec,
                1
            ),
            alpha (
                #3689e6,
                1	
            )
        );
}
```

## Blueberry Blue
Blueberry 500 to Blueberry 700

![blueberry blue](https://user-images.githubusercontent.com/523210/36067458-033dc8c2-0ebe-11e8-9985-047c3102ab11.png)

``` css
.scale.highlight.left {
    border-color: alpha (#000, 0.5);
    background-image:
        linear-gradient(
            to bottom,
            alpha (
		#3689e6,
                1.0
            ),
            alpha (
                #0d52bf,
                1
            )
        );
}
```

(originally opened as  granite issue: https://github.com/elementary/granite/issues/150)
