### ISSUE TITLE
Style Dazzle completion entry

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#411]
Epiphany upstream is using a new LibDazzle completion entry, which has a nice animated completion dropdown. The problem is, the default styling in elementary OS is super ugly/broken. We should see if there's something better we can be doing for the styling.

**Comment by cassidyjames** [comment]
What it's supposed to look like (and does in Adwaita) from [Twitter](https://twitter.com/hergertme/status/1041891152272580608):

![Screenshot](https://pbs.twimg.com/media/DnWKUwzUYAAfRCb.jpg:large)

What it looks like right now:

![screenshot from 2018-10-01 16 46 22](https://user-images.githubusercontent.com/611168/46320124-17384800-c59a-11e8-8609-bdd48b7357e7.png)

**Comment by cassidyjames** [comment]
You can grab the nightly build of Epiphany as a Flatpak from [webkit.org/downloads](https://webkit.org/downloads/).

**Comment by cassidyjames** [comment]
It looks like Dazzle is expecting some variables that we don't set:

https://github.com/GNOME/libdazzle/blob/694ab037fb316e702925776956c15ea87ed9b62a/data/themes/shared/shared-suggestions.css

Setting them seems to make the suggestion at least readable, though it looks like Dazzle is also not opposed to carrying stylesheet-specific fixes: https://github.com/GNOME/libdazzle/tree/694ab037fb316e702925776956c15ea87ed9b62a/data/themes

**Comment by cassidyjames** [comment]
Currently working with something like this in the Inspector:

```css
@define-color content_view_bg @bg_color;

dzlsuggestionpopover > revealer > box {
    border-radius: 4px;
    border: 1px solid alpha (#000, 0.3);
    box-shadow:
        inset 0 -1px 0 0 alpha (@bg_highlight_color, 0.5),
        0 3px 6px alpha (#000, 0.16),
        0 3px 6px alpha (#000, 0.23);
    margin: 24px 12px;
    text-shadow: none;
}

dzlsuggestionpopover > revealer > box > elastic > scrolledwindow > viewport > list > row:selected .title {
  color: @theme_fg_color;
}
```
