### ISSUE TITLE
Don't force buttons in action bars inside of sidebars to fullcolor

### ISSUE THREAD

**Issue by cassidyjames** [elementary/stylesheet#553]
Required for https://github.com/elementary/code/pull/569

**Comment by jtrees** [comment]
The relevant code for this is in `gtk-widgets.css`:

```css
.sidebar,
.sidebar.view,
.sidebar list,
.source-list,
.source-list.view {
    background-color: shade (@bg_color, 0.92);
    color: mix (@bg_color, @text_color, 0.77);
    -gtk-icon-style: regular;
    -GtkTreeView-horizontal-separator: 1px;
    -GtkTreeView-vertical-separator: 6px;
}
```

How specific should this change be?

The simplest thing would be to simply remove the `-gtk-icon-style: regular;` from the snippet above but I don't know all the side-effects this will result in.

Alternatively and going by the way the issue is phrased, perhaps you're looking more for something like this?

```css
.sidebar .horizontal.inline-toolbar {
  -gtk-icon-style: requested;
}
```

**Comment by cassidyjames** [comment]
@jtrees yeah I think this would be right:

```css
.sidebar .inline-toolbar,
.source-list .inline-toolbar {
    -gtk-icon-style: requested;
}
```
