### ISSUE TITLE
[$15] Sidebar in Files inactive state is wrong

### ISSUE THREAD

**Issue by gwutz** [elementary/stylesheet#63]
In Files there is a special Selector for that tree view which is wrong styled in gtk+ 3.22

Relevant Screenshot:

![bildschirmfoto von 2017-01-23 21 49 35](https://cloud.githubusercontent.com/assets/373597/22222109/db7a5d9a-e1b5-11e6-99c6-960a39e44538.png)

**Comment by sourenaraya** [comment]
[this fragment is responsible for this issue](https://github.com/elementary/stylesheet/blob/master/gtk-3.0/gtk-widgets.css#L3514-L3523)
```css
.sidebar .list-row,
.sidebar .view,
.sidebar-item,
.sidebar-row,
.source-list .view {
    border-color: transparent;
    border-style: solid;
    border-width: 1px 0;
    text-shadow: 0 1px @text_shadow_color;
}
```
