### ISSUE TITLE
Insensitive arrow on notebook doesn't look insensitive

### ISSUE THREAD

**Issue by tintou** [elementary/stylesheet#870]
With multiple tabs open, there are arrows on the GtkNotebook, when there is no other tab on the left or right side, the arrow is insensitive.

How it currently looks like:
![Capture d'écran du 2020-10-28 13 08 34@2x](https://user-images.githubusercontent.com/745535/97434069-bfa66b00-191e-11eb-84dd-da100c439a77.png)

How it should look like:
![Capture d'écran du 2020-10-28 13 08 46@2x](https://user-images.githubusercontent.com/745535/97434080-c3d28880-191e-11eb-9947-915f5f18fedb.png)

CSS Snippet that I put in the GTK inspector, for information only as I'm far from being knowledgeable in CSS and GTK-CSS:
```css
notebook tabs arrow:insensitive {
    -gtk-icon-effect: dim;
    color: rgb(153,153,153)
}
```
